### ISSUE TITLE
Requesting for add the new documents

### ISSUE THREAD

**Issue by Ellappan-veera** [Ellappan-gif/DevOps-Ecare#6]
Hi Ellappan
[Azure export.txt](https://github.com/Ellappan-gif/DevOps-Ecare/files/3453774/Azure.export.txt)

 please add this report in your dcouments.

**Comment by Ellappan-veera** [comment]
plz review and check

**Comment by Ellappan-gif** [comment]
Dear Veera,

 Thanks for adding feature, will check and let u know the same. keep supporting on this.

**Comment by Ellappan-gif** [comment]
Dear Veera,


  We have added as you mentioned the issue. thanks for making our product great.
